-- Existing 8-table schema only. Preserves all data and changes the review RPC.
-- Correct Seoul Songpa/Gangdong eligibility and add the read-only review_contract RPC.
-- Existing v1 reviews remain immutable.
-- Local proposal: not applied remotely. See fastapi-implementation-plan.md.
-- Generated by scripts/build_supabase_design.mjs; do not edit this copy.
begin;
create or replace function public.save_scenario_review(
  p_organization_id uuid, p_scenario_id uuid, p_user_id uuid, p_idempotency_key uuid,
  p_request_sha256 text, p_baseline_status text, p_baseline_snapshot jsonb,
  p_evidence_release_id uuid default null
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  v_role text;
  v_scenario public.simulation_scenarios;
  v_review public.scenario_reviews;
  v_stat public.policy_evidence_statistics;
  v_status text;
  v_segment text;
  v_response jsonb;
begin
  select role into v_role from public.organization_members
    where organization_id = p_organization_id and user_id = p_user_id for share;
  if v_role is null or v_role not in ('admin', 'editor') then
    raise exception using errcode = '42501', message = 'REVIEW_FORBIDDEN';
  end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('review:' || p_organization_id::text || ':' || p_idempotency_key::text, 0));
  select * into v_review from public.scenario_reviews
    where organization_id = p_organization_id and idempotency_key = p_idempotency_key;
  if found then
    if v_review.request_sha256 <> p_request_sha256 or v_review.scenario_id <> p_scenario_id then
      raise exception using errcode = '23505', message = 'IDEMPOTENCY_CONFLICT';
    end if;
    return to_jsonb(v_review);
  end if;
  select * into v_scenario from public.simulation_scenarios
    where organization_id = p_organization_id and id = p_scenario_id for share;
  if not found then raise exception using errcode = '42501', message = 'SCENARIO_NOT_ACCESSIBLE'; end if;
  if p_baseline_snapshot is null or jsonb_typeof(p_baseline_snapshot) <> 'object'
    or (p_baseline_snapshot->'request'->>'regionId') is distinct from v_scenario.region_id
    or (p_baseline_snapshot->'request'->>'districtId') is distinct from v_scenario.district_id
    or not coalesce(p_baseline_snapshot->>'capturedAt' ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?(Z|[+-][0-9]{2}:[0-9]{2})$', false)
    then raise exception 'INVALID_BASELINE'; end if;
  perform (p_baseline_snapshot->>'capturedAt')::timestamptz;
  foreach v_segment in array array['summary','diagnosis'] loop
    v_response := p_baseline_snapshot->v_segment;
    if jsonb_typeof(v_response) = 'object' then
      if (v_response->>'district') is distinct from v_scenario.district_id
        or not coalesce(v_response->>'baseYm' ~ '^[0-9]{4}(0[1-9]|1[0-2])$', false)
        or not coalesce(v_response->>'fetchedAt' ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?(Z|[+-][0-9]{2}:[0-9]{2})$', false)
        then raise exception 'INVALID_BASELINE'; end if;
      perform (v_response->>'fetchedAt')::timestamptz;
    end if;
  end loop;
  if v_scenario.policy_code not in ('festival', 'night') then
    v_status := 'unsupported_policy';
  elsif v_scenario.policy_code = 'festival' and not (
    v_scenario.district_id in ('12210','12240','12270','12300','12330')
    or left(v_scenario.district_id,2) = '11'
    or (left(v_scenario.district_id,2) in ('26','27','28','30','31') and substring(v_scenario.district_id from 3)::integer < 700)
  ) then
    v_status := 'out_of_scope';
  elsif p_evidence_release_id is null then
    v_status := 'not_imported';
  else
    v_segment := case when v_scenario.policy_code = 'festival' then 'metroGu' else 'night' end;
    select * into v_stat from public.policy_evidence_statistics
      where release_id = p_evidence_release_id and outcome = 'outside' and segment = v_segment;
    if not found then raise exception 'EVIDENCE_RELEASE_NOT_FOUND'; end if;
    v_status := case when v_stat.sample_count > 0 and v_stat.ci_lower_pct > 0 then 'available' else 'insufficient_evidence' end;
  end if;
  insert into public.scenario_reviews(organization_id, scenario_id, created_by, evidence_statistic_id,
    reference_status, selection_rule_version, baseline_status, baseline_snapshot, idempotency_key, request_sha256)
  values (p_organization_id, p_scenario_id, p_user_id, v_stat.id, v_status, 'festival-reference-v2',
    p_baseline_status, p_baseline_snapshot, p_idempotency_key, p_request_sha256) returning * into v_review;
  return to_jsonb(v_review);
end;
$$;
revoke all on function public.save_scenario_review(uuid,uuid,uuid,uuid,text,text,jsonb,uuid) from public, anon, authenticated;
grant execute on function public.save_scenario_review(uuid,uuid,uuid,uuid,text,text,jsonb,uuid) to service_role;

-- Read-only deployment contract: FastAPI checks this before collecting/saving new reviews.
create or replace function public.review_contract() returns jsonb
language sql stable security invoker set search_path = '' as $$
  select jsonb_build_object('rule_version', 'festival-reference-v2', 'baseline_schema_version', 1);
$$;
revoke all on function public.review_contract() from public, anon, authenticated;
grant execute on function public.review_contract() to service_role;
commit;
